<?php

use Drupal\layout_paragraphs\LayoutParagraphsLayout;
use Drupal\layout_paragraphs\LayoutParagraphsSection;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_node_prepare_form().
 */
function uni_page_node_prepare_form($node, $operation, $form_state) {
  if ($operation !== 'default') return;
  if (!$node->hasField('uni_page_items')) return;

  $paragraph_types = \Drupal::service('entity_type.bundle.info')->getBundleInfo('paragraph');
  if (!array_key_exists('uni_section', $paragraph_types)) return;
  if (!array_key_exists('uni_text', $paragraph_types)) return;

  $uni_section = Paragraph::create([ 'type' => 'uni_section' ]);
  $section = new LayoutParagraphsSection($uni_section);
  $section->setSettings([ 'layout' => 'uni_1col' ]);

  $layout = new LayoutParagraphsLayout($node->get('uni_page_items'));
  $layout->appendComponent($uni_section);
}
